name: publish
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
      - name: Checkout repo
        if: steps.changes.outputs.src == 'true'
        uses: actions/checkout@v4

      - if: steps.changes.outputs.src == 'true'
        run: |
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.USER_EMAIL }}"

      - name: Use Node ${{ matrix.node }}
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        if: steps.changes.outputs.src == 'true'
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 6.0.2

      - name: Install deps and build (with cache)
        if: steps.changes.outputs.src == 'true'
        run: pnpm install --no-frozen-lockfile

      - if: steps.changes.outputs.src == 'true'
        run: pnpm prisma:generate

      - name: Lint
        if: steps.changes.outputs.src == 'true'
        run: pnpm lint

      - if: steps.changes.outputs.src == 'true'
        run: pnpm prisma:deploy

      - name: Test
        if: steps.changes.outputs.src == 'true'
        run: pnpm test -- --ci --coverage --maxWorkers=2

      - name: Build
        if: steps.changes.outputs.src == 'true'
        run: pnpm build

      - name: Bump version
        if: steps.changes.outputs.src == 'true'
        uses: qzb/standard-version-action@v1.0.13



      - if: steps.changes.outputs.src == 'true'
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git push --follow-tags origin main

      - if: steps.changes.outputs.src == 'true'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}


